# Generated by Django 3.0.3 on 2020-06-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_pediatras',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Generar_cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField()),
                ('Hora', models.TimeField()),
                ('Comentarios', models.TextField(max_length=200)),
                ('Pediatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Registro_Pediatras')),
            ],
        ),
    ]
