# Generated by Django 3.0.3 on 2020-06-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20200609_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_pediatras',
            name='Email',
        ),
    ]
