# Generated by Django 3.0.3 on 2020-06-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_registro_pediatras_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='generar_cita',
            name='Email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
