# Generated by Django 3.0.3 on 2020-06-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_auto_20200610_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generar_cita',
            name='Email',
            field=models.EmailField(default='cesardeleonga@gmail.com', max_length=254, null=True),
        ),
    ]
