# Generated by Django 3.0.3 on 2020-06-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_auto_20200610_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generar_cita',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
